name: ml-nlp
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Core
  - python=3.11
  - pip
  - setuptools
  - wheel

  # PyTorch + CUDA
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - torchtext=0.17.2
  - pytorch-cuda=12.1 # from NVIDIA channel

  # Science / ML
  - numpy=1.26.4
  - scipy
  - pandas=2.3.1
  - scikit-learn
  - tqdm=4.66.5

  # NLP / Transformers
  - transformers
  - tokenizers
  - datasets=4.0.0
  - sentencepiece=0.2.1
  - spacy

  # Language Models
  - language-data=1.3.0
  - spacy-model-de_core_news_sm
  - spacy-model-en_core_web_sm
  - pip:
      - langcodes==3.5.0

  # Visualization
  - matplotlib
  - seaborn

  # Jupyter / Dev
  - jupyterlab
  - ipykernel
  - ipywidgets

  # Logging / Monitoring
  - tensorboard=2.20.0
  - wandb
